### ISSUE TITLE
akamai sensor data

### ISSUE THREAD

**Issue by Numenorean** [Categorically/hilton_honor_android_login#1]
hello. How can i find an algorithm to generate a sensor data? if you can reverse it, i would buy it

**Comment by Categorically** [comment]
> hello. How can i find an algorithm to generate a sensor data? if you can reverse it, i would buy it

Generating sensor data is out of scope for this project.
The data is generated by Hilton using Akamai bot manager SDK.
Tacobell and Home Depot use the same data.
